### Create a new client
POST http://localhost:3333/clients
Content-Type: application/json

{
  "name": "Johnny fontes rabelo",
  "telephone": "5523996738213",
  "email": "john.doe@example.com",
  "passToPass": {},
  "observation": "New client",
  "plan": "Recorrente",
  "date": "2024-07-13T00:00:00Z",
  "suporteId": 7,
  "updatedAt": "2024-07-13T00:00:00Z"
}

### Get all clients
GET http://localhost:3333/clients

### Get a specific client
GET http://localhost:3333/clients/3

### Update a client
PUT http://localhost:3333/clients/1
Content-Type: application/json

{
  "secondPayment": true
}

### Delete a client
DELETE http://localhost:3333/clients/29

###

GET http://localhost:3333/clientsWithSuporte

###

POST http://localhost:3333/suportes
Content-Type: application/json

{
  "name": "Luan",
  "email": "luan@whatsmenu.com.br",
  "type": "Suporte 1",
  "number": "5512978678"
}

###

GET http://localhost:3333/suportes/1/clients
Accept: application/json
